name: elhombrearnuncio
favicon: null
layout_spectrum: 0.00086
typography_spectrum: 0.49734
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#34180f'
    - '#524231'
    - '#6b6b5a'
    - '#94948b'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
