name: elhombrearnuncio
favicon: null
layout_spectrum: 0.7125536072999239
typography_spectrum: 0.49734
title: 'Indexing the creative ego of Juan Arnuncio through design & art direction'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#34180f'
    - '#524231'
    - '#6b6b5a'
    - '#94948b'
  brandStrength: 0.39635395514778793
  lightness: 0.5274349225219339
  saturation: 0.6569683314301074
  rhythmicContrast: 0.9080232963897288
purpose: []
